version: '3.8'

services:
  sqli-lab:
    build: .
    container_name: sql-injection-lab
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app  # Esto permite que si cambias código, se actualice (útil desarrollo)
    restart: always